### ISSUE TITLE
karolos/manager.py file does not exist in the current version of the code

### ISSUE THREAD

**Issue by ChristosPeridis** [tmdt-buw/karolos#7]
Hello dear Christian and dear Thunfisch,

When attempting to execute an experiment by launching a manager by typing the command:

python karolos/manager.py

I received the following message:

python: can't open file 'karolos/manager.py': [Errno 2] No such file or directory

I checked the file structure of the repository and I was unable to find the 'manager.py' file in the given file path. In fact I was not able to detect the specific file anywhere in the repository. Please guide me regarding What actions I must take to run the example code and make sure that everything runs as expected.

Thank you very much for your valuable help!!!

Kind regards,

Christos Peridis

**Comment by chrisbitter** [comment]
Hey Christos,

oh no, forgot to update the docs!

We renamed the manager.py to experiment.py, as Experiment better reflects
what the code does (running a RL experiment).

It's also no longer possible to run an experiment from the file. Take a
look at the examples, e.g. examples/train_sac_panda_reach.py

Cheers Christian

**Comment by chrisbitter** [comment]
Updated the Readme. Closing this issue.

**Comment by ChristosPeridis** [comment]
Hello dear Christian,

Thank you very much for the update! It was very useful and helped me understand what the issue was and and how to proceed working with the API.

Many thanks again for all the valuable help and support!

Kind regards,

Christos Peridis
