### ISSUE TITLE
Issue when attempting to install the suggested version of OpeanAI Gym (gym==0.18.0)

### ISSUE THREAD

**Issue by ChristosPeridis** [tmdt-buw/karolos#8]
Hello dear Christian and dear Thunfisch,

Another problem that also occurred while attempting to install the OpenAI Gym version 0.18.0 in the karolos conda environment was the following:

Collecting gym==0.18.0
  Using cached gym-0.18.0.tar.gz (1.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Any suggestions on how I might be able to overcome this issue?

Thank you very much for your valuable help!

Kind regards,

Christos Peridis

**Comment by chrisbitter** [comment]
Looks like `gym=0.18.0` made some trouble. 
Hopefully this is fixed by using the newest gym version. Closing this issue (duplicate to #5)
